### ISSUE TITLE
gitattributes

### ISSUE THREAD

**Issue by BarbzYHOOL** [mindsear/mod-MorphAll-command-AzerothCore#1]
Did you remove .editorconfig and gitattributes???

That's BAD BAD BAD BAD @mindsear 
It's there to avoid crossplatforms errors

**Comment by mindsear** [comment]
I apologize.
I mean I have those files in my local folder, when I uploaded all files seemed like it skipped those two for some reason. 
Maybe, the reason is that they start with a **.** (dot) ?

**Comment by BarbzYHOOL** [comment]
maybe (on windows)

you should use the script in modules/ to kickstart a module, it has everything and it takes 2 seconds !

But yes, these files are useful

**Comment by mindsear** [comment]
I will keep that in mind next time.
Thanks.

**Comment by BarbzYHOOL** [comment]
I forked it

btw still missing .git_commit_template.txt (it's not essential though but there is the other related file already)

**Comment by mindsear** [comment]
I have added .git_commit_template.txt file to the azerothcore module.
